exclude: [
  ".rvmrc",
  ".rbenv-version",
  "config.rb",
  "CNAME",
  "Procfile",
  "README",
  "Gemfile",
  "Gemfile.lock",
  "sass",
  "Vagrantfile",
  "bootstrap.sh",
  "vendor",
  ".travis.yml"
]

title     : This is my homepage
url       : http://reyhan.org
tagline   : wubwubwub
author    : Rey Dhuny
permalink : /:year/:month/:title.html
encoding  : utf-8
markdown  : kramdown
port      : 7777
timezone  : Europe/London
