permalink: /:year/:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README", "Rakefile", "changelog.md", "sass_converter.rb", "Gemfile", "Gemfile.lock"]

baseurl: /

title : rey.github.com
tagline: wubwubwub
author :
  name : Rey Dhuny