exclude: ["README.md","Gemfile", "Gemfile.lock", "config.rb", "sass", "CNAME", "Procfile"]

live_url: http://reyhan.org

title: This is my homepage

tagline: wubwubwub

author:
  name: Rey Dhuny

timezone: Europe/London

permalink: /:year/:month/:title.html

markdown: kramdown

encoding  : utf-8
