permalink: /:year/:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README", "Rakefile", "changelog.md", "haml_converter.rb"]

baseurl: /

title : rey.github.com
tagline: wubwubwub
author :
  name : Rey Dhuny